version: "2"
services:
  cnitch:
    image: quay.io/nicholasjackson/cnitch:latest
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 100
    command: ["--hostname=localhost", "--statsd-server=statsd:9125"]
  dogstatsd:
    image:  datadog/docker-dogstatsd:latest
    environment:
      - API_KEY=${API_KEY}
      - LOG_LEVEL=DEBUG
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  statsd:
    image: prom/statsd-exporter
  graphana:
    build: 
      context: .
      dockerfile: DockerfileGrafana
    ports:
      - 3000:3000
