global:
  scrape_interval:     10s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'statsd'	
    static_configs:
      - targets: ['statsd:9102']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
